root: "."

SyntaxError:
  enabled: true

LiquidTag:
  enabled: true
  min_consecutive_statements: 5

UnknownFilter:
  enabled: true
  exclude:
    - templates/gift_card.liquid

MissingRequiredTemplateFiles:
  enabled: true

TemplateLength:
  enabled: true
  max_length: 600

NestedSnippet:
  enabled: true
  max_nesting_level: 3

RequiredDirectories:
  enabled: true

ValidSchema:
  enabled: true

UnusedAssign:
  enabled: true

UndefinedObject:
  enabled: true
  exclude_snippets: true

DeprecatedFilter:
  enabled: true

DefaultLocale:
  enabled: true

TranslationKeyExists:
  enabled: true

RequiredLayoutThemeObject:
  enabled: true

ContentForHeaderModification:
  enabled: true

MissingTemplate:
  enabled: true

RemoteAsset:
  enabled: false

AssetSizeCSS:
  enabled: true
  threshold_in_bytes: 200000

AssetSizeJavaScript:
  enabled: true
  threshold_in_bytes: 100000

ImgWidthAndHeight:
  enabled: false

ImgLazyLoading:
  enabled: true

ParserBlockingJavaScript:
  enabled: true

ParserBlockingScriptTag:
  enabled: true
